### PR TITLE
Adding More on Databases minilecture

### PR DESCRIPTION
**Pull request by comjosh64**
Added "More on Databases" video to "Minilecture" section.  Thanks to Sam for recording this lecture!

### CODE REVIEW

**Comment by comjosh64** [comment]
Terribleplan/Kegan?
I think I got all the fields updated properly this time. Thanks for
accepting the pull request so quick!  If you have the screen cast up I was
going to link to it within the video.

Josh

**Comment by terribleplan** [comment]
Ahh, you were close, you updated into "master" again. Please do a pull into gh-pages, that is the branch that runs the site.

I have been having issues with the way I recorded my screen, the video is in some weird format that a lot of things are detecting as corrupted.

**Comment by terribleplan** [comment]
If you can get the changes pushed within 20 minutes I can pull it, any later and I will have to do it tonight, or Mike will have to.

**Comment by comjosh64** [comment]
I'm trying to figure out how to change my local files to sync to the other
branch.  It seems to default to master.

**Pull request merged**
