### PR TITLE
Changed "lesson" to match MiniLectures.

### PR DESCRIPTION
**Pull request by comjosh64**

### CODE REVIEW

**Comment by comjosh64** [comment]
I'm trying fix a project that isn't broken!  The "sneak peek" link isn't
working anymore, and I thought it had something to do with the changes I
made. I saw that you had to fix lesson.json and the comma issue in
videos.json, so I I thought you were getting the same error that I was. I
kept thinking: Why does the root directory (
launchcode-tvhttps://github.com/MoMenne/launchcode-tv/ ) now
contains the directory tree for the project instead of them being
in the /app directory?  I noticed the difference and thought I'd found the
bug right before finding the link to http://tv.launchcode.us/ and
everything is working fine.  I feel a little silly.

Josh

**Comment by mpmenne** [comment]
Hey Josh, 

That's my bad!    Kegan refactored it to work on GitHub pages and to be hosted @ tv.launchcode.us ....  To use Github pages we have to the code in the gh-pages branch.  I merged all of your changes over to the other branch, and I just need to delete the master to prevent confusion.

Cheers,
Mike

**Comment by mpmenne** [comment]
Josh I just saw all of the video magic you put in the mini lecture.  Awesome job man!

**Comment by comjosh64** [comment]
Thanks!  There are a few tweeks I'd like to still make, but I wanted to
have it online right away.  Now that I know git-hub a little better it
should not be difficult to post a re-edited version and update the url.

**Pull request merged**
